# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/katerinarias',
                'doc_host': 'https://katerinarias.github.io',
                'git_url': 'https://github.com/katerinarias/katerinarias',
                'lib_path': ''},
  'syms': {'katerinarias.core': {'katerinarias.core.foo': ('core.html#foo', 'katerinarias/core.py')}, 'katerinarias.setup': {}}}
