project:
  type: website

format:
  html:
    theme:
      light: [lightly, theme-light.scss]
      dark: [darkly, theme-dark.scss]
    css: styles.css
    toc: false
    keep-md: true
    page-layout: full
    anchor-sections: false
  commonmark: default

website:
  navbar:
    title: "katerinarias"
    search: true
    logo: ./assets/logo.png
    left:
      - text: Members
        href: members.qmd
      - text: Publications
        href: publications.qmd
      - text: Projects
        href: projects.qmd
      - text: Contact
        href: contact.qmd
    custom-css: styles.css

metadata-files: [nbdev.yml]
