project:
  type: website

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    css: styles.css
    toc: false
    keep-md: true
    page-layout: full
  commonmark: default

website:
  navbar:
    title: "katerinarias"
    search: true
    logo: logo.png
    left:
      - text: Members
        href: members.qmd
      - text: Publications
        href: publications.qmd
      - text: Projects
        href: projects.qmd
      - text: Location
        href: location.qmd
    custom-css: styles.css

metadata-files: [nbdev.yml]